name: Sync LeetCode
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:   # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
